# @format

name: 🐛 Bug Report
description: Report a bug or issue with FleetFusion
title: "[Bug]: "
labels: ["Bug", "Priority-Medium"]
assignees:
    - DigitalHerencia
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

    - type: input
      id: summary
      attributes:
          label: Bug Summary
          description: A brief, clear description of what the bug is
          placeholder: "Dashboard crashes when accessing vehicle details"
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Detailed Description
          description: Provide a detailed description of the issue
          placeholder: |
              Steps to reproduce:
              1. Navigate to...
              2. Click on...
              3. Error occurs...

              Expected behavior:
              The dashboard should...

              Actual behavior:
              Instead, the dashboard...
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority Level
          description: How urgent is this bug?
          options:
              - High - Critical issue, blocks core functionality
              - Medium - Important but workaround available
              - Low - Minor issue, cosmetic or edge case
          default: 1
      validations:
          required: true

    - type: dropdown
      id: component
      attributes:
          label: Component
          description: Which part of FleetFusion is affected?
          options:
              - Dashboard
              - Vehicle Management
              - Driver Management
              - Dispatch
              - IFTA Compliance
              - Analytics
              - Authentication
              - Multi-tenancy
              - API
              - Database
              - Other
      validations:
          required: true

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Technical details about your environment
          placeholder: |
              - Browser: Chrome 120.0
              - OS: Windows 11
              - FleetFusion Version: v1.2.0
              - Database: Neon PostgreSQL
      validations:
          required: false

    - type: textarea
      id: dependencies
      attributes:
          label: Dependencies/Blockers
          description: Does this issue depend on or block other issues?
          placeholder: |
              Depends on #123
              Blocks #456
      validations:
          required: false

    - type: checkboxes
      id: milestone
      attributes:
          label: Target Milestone
          description: Which release should this be included in?
          options:
              - label: MVP Launch (June 16, 2025)
              - label: Q3 2025 Release (July 1, 2025)
              - label: Testing & Automation Hardening (July 15, 2025)
              - label: Post-Launch Enhancements (August 30, 2025)
