# @format

name: 🐛 Bug Report
description: File a bug report to help us improve FleetFusion
title: "[Bug]: "
labels: ["bug", "triage"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

    - type: checkboxes
      attributes:
          label: Prerequisites
          description: Please confirm the following before submitting
          options:
              - label: I have searched existing issues to ensure this is not a duplicate
                required: true
              - label: I have read the [Merge Conflict Resolution Guide](../docs/merge-conflict-resolution.md) if this relates to PR conflicts
                required: false

    - type: textarea
      attributes:
          label: Bug Description
          description: A clear and concise description of what the bug is
          placeholder: Describe what happened...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps to Reproduce
          description: Steps to reproduce the behavior
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected Behavior
          description: A clear and concise description of what you expected to happen
          placeholder: What should have happened?
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots/Logs
          description: If applicable, add screenshots or logs to help explain your problem
          placeholder: Add screenshots or paste logs here...

    - type: dropdown
      attributes:
          label: Environment
          description: What environment did this occur in?
          options:
              - Development
              - Staging
              - Production
              - Local
      validations:
          required: true

    - type: input
      attributes:
          label: Browser/Device
          description: What browser or device were you using?
          placeholder: e.g., Chrome 120, Safari on iPhone 15

    - type: textarea
      attributes:
          label: Additional Context
          description: Add any other context about the problem here
          placeholder: Any additional information...
