# @format

name: 📚 Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["Documentation", "Priority-Low"]
assignees:
    - DigitalHerencia
body:
    - type: markdown
      attributes:
          value: |
              Help us improve FleetFusion's documentation! Please provide details about what needs to be added or updated.

    - type: input
      id: summary
      attributes:
          label: Documentation Summary
          description: A brief description of what documentation is needed
          placeholder: "Add API authentication examples to developer guide"
      validations:
          required: true

    - type: dropdown
      id: doc_type
      attributes:
          label: Documentation Type
          description: What type of documentation needs attention?
          options:
              - User Guide - End-user documentation
              - Developer Documentation - Technical/API docs
              - Setup/Installation Guide
              - Configuration Guide
              - Troubleshooting Guide
              - Code Comments
              - README Updates
              - Architecture Documentation
          default: 0
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Detailed Description
          description: What specific documentation is missing or needs improvement?
          placeholder: |
              Current state:
              The current docs don't explain...

              What's needed:
              Users need documentation that explains...

              Suggested content:
              - How to...
              - Examples of...
              - Common pitfalls...
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority Level
          description: How important is this documentation?
          options:
              - High - Critical for user onboarding/development
              - Medium - Important for complete understanding
              - Low - Nice to have, improves clarity
          default: 2
      validations:
          required: true

    - type: input
      id: file_location
      attributes:
          label: File/Location
          description: Where should this documentation be located?
          placeholder: "doc/api/authentication.md or README.md section"
      validations:
          required: false

    - type: textarea
      id: audience
      attributes:
          label: Target Audience
          description: Who is the primary audience for this documentation?
          placeholder: |
              - End users (fleet managers)
              - Developers integrating with API
              - System administrators
              - Contributors to the project
      validations:
          required: false

    - type: textarea
      id: dependencies
      attributes:
          label: Dependencies/Blockers
          description: Does this documentation depend on other issues or features?
          placeholder: |
              Depends on #123 (API implementation)
              Blocks #456 (User onboarding)
      validations:
          required: false

    - type: checkboxes
      id: milestone
      attributes:
          label: Target Milestone
          description: Which release should this be included in?
          options:
              - label: MVP Launch (June 16, 2025)
              - label: Q3 2025 Release (July 1, 2025)
              - label: Testing & Automation Hardening (July 15, 2025)
              - label: Post-Launch Enhancements (August 30, 2025)
