# @format

name: ✨ Feature Request
description: Suggest a new feature for FleetFusion
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please provide as much detail as possible.

    - type: checkboxes
      attributes:
          label: Prerequisites
          description: Please confirm the following before submitting
          options:
              - label: I have searched existing issues to ensure this is not a duplicate
                required: true
              - label: I have read the [Merge Conflict Resolution Guide](../docs/merge-conflict-resolution.md) if I plan to contribute this feature
                required: false

    - type: textarea
      attributes:
          label: Feature Description
          description: A clear and concise description of the feature you'd like to see
          placeholder: Describe the feature...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Problem/Use Case
          description: What problem does this feature solve? What's your use case?
          placeholder: Explain the problem this feature would solve...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Proposed Solution
          description: How would you like this feature to work?
          placeholder: Describe your proposed solution...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Alternative Solutions
          description: Have you considered any alternative solutions or workarounds?
          placeholder: Describe alternatives you've considered...

    - type: dropdown
      attributes:
          label: Feature Category
          description: Which area of FleetFusion does this feature relate to?
          options:
              - Vehicle Management
              - Driver Management
              - Dispatch/Routing
              - Compliance/IFTA
              - Analytics/Reporting
              - Settings/Configuration
              - Admin/Multi-tenant
              - Mobile App
              - Other
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Priority
          description: How important is this feature to you?
          options:
              - Nice to have
              - Important
              - Critical
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional Context
          description: Add any other context, mockups, or examples about the feature
          placeholder: Any additional information, screenshots, or mockups...
