name: "Add to FleetFusion Project"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue/PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/DigitalHerencia/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}