# .github/workflows/pr-validation.yml
name: PR Validation
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^(feat|fix|docs|test|refactor|config):.+ ]]; then
            echo "❌ PR title must follow format: [type]: description"
            exit 1
          fi
      
      - name: Check Branch Name
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|fix|docs|test|refactor|config)/.+ ]]; then
            echo "❌ Branch must follow format: type/description"
            exit 1
          fi